server:
  port: 8081

spring:
  application:
    name: store-admin
  rabbitmq:
    host: 192.168.0.17
    port: 5672
    username: admin
    password: 1234
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

